[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = { version = "0.6.0" }
adw = {package = "libadwaita", version = "0.3"}
home = { version = "0.5.4" }
serde = "1.0.158"
serde_derive = "1.0.158"
toml = "0.7.3"
glib = {}
gio = {}
xdg = {}

